#!/usr/bin/env sh

# This file is part of the Dotcloud Wordpress Deployment package.
# 
# (c) Quentin Pleplé <quentin.pleple@gmail.com>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Reads environment.json and config MySQL values in wp-config.php
./dotcloud-scripts/feed-wp-config.sh

# Move wp-content to make it persistent
./dotcloud-scripts/persist-wp-content.php